wilken/keypair type fix (#185)
* Add failing test case for #184

```
--- FAIL: TestRunConfigPrepare_TemporaryKeyPairTypeDefault (0.00s)
    --- FAIL: TestRunConfigPrepare_TemporaryKeyPairTypeDefault/setting_a_temporary_key_pair_name_should_set_default_key_pair_type (0.00s)
        run_config_test.go:253: keypair type should have defaulted to rsa

```

* Fix defaults for SSHTemporaryKeyPairType when SSHTemporaryKeyPairName is set

Test Results after change
```
~>  go test -count=1 ./... -run="TestRunConfigPrepare_TemporaryKeyPairType"
?       github.com/hashicorp/packer-plugin-amazon       [no test files]
ok      github.com/hashicorp/packer-plugin-amazon/builder/chroot        0.957s [no tests to run]
ok      github.com/hashicorp/packer-plugin-amazon/builder/common        0.654s
?       github.com/hashicorp/packer-plugin-amazon/builder/common/awserrors      [no test files]
?       github.com/hashicorp/packer-plugin-amazon/builder/common/ssm    [no test files]
ok      github.com/hashicorp/packer-plugin-amazon/builder/ebs   1.841s [no tests to run]
?       github.com/hashicorp/packer-plugin-amazon/builder/ebs/acceptance        [no test files]
ok      github.com/hashicorp/packer-plugin-amazon/builder/ebssurrogate  1.561s [no tests to run]
ok      github.com/hashicorp/packer-plugin-amazon/builder/ebsvolume     1.656s [no tests to run]
ok      github.com/hashicorp/packer-plugin-amazon/builder/instance      1.289s [no tests to run]
ok      github.com/hashicorp/packer-plugin-amazon/datasource/ami        0.522s [no tests to run]
ok      github.com/hashicorp/packer-plugin-amazon/datasource/parameterstore     1.402s [no tests to run]
ok      github.com/hashicorp/packer-plugin-amazon/datasource/secretsmanager     0.775s [no tests to run]
?       github.com/hashicorp/packer-plugin-amazon/post-processor/import [no test files]
?       github.com/hashicorp/packer-plugin-amazon/version       [no test files]

```

Closes #184